### ISSUE TITLE
Error building assets

### ISSUE THREAD

**Issue by DK15** [GroovinChip/Flutter-Community-Challenges#12]
I am getting below error while trying to build:

```
Error detected in pubspec.yaml:
No file or variants found for asset: properties/properties.yaml.
```
Where is `properties.yaml` located ?

**Comment by GroovinChip** [comment]
This file, as well as the google-services.json file, are hidden via gitignore for security purposes. If you are serious about contributing, DM me on Discord and I can provide the files
